[package]
name = "trade_robot"
version = "0.1.3"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["blocking"] }
serde_json = "1.0.117"
chrono = "0.4.38"
figlet-rs = "0.1.5"
log = "0.4.21"
